# -*- coding: utf-8 -*-
"""metode simpson

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xG8m32GHYOl2T4jSgSLwvJ7GN92shtF
"""



import numpy as np
import matplotlib.pyplot as plt

# Fungsi yang akan diintegralkan
def func(x):
    return x**-3 + np.cos(x)

# Batas integrasi
a = 1.0  # Batas bawah
b = 5.0  # Batas atas
n = 151  # Jumlah subinterval (harus ganjil untuk metode Simpson)

# Metode Simpson
if n % 2 == 0:
    n += 1  # Jika n genap, tambahkan 1 agar menjadi ganjil

x = np.linspace(a, b, n)  # Buat partisi interval
dx = (b - a) / (n - 1)  # Lebar setiap subinterval

# Inisialisasi hasil
hasil = func(x[0]) + func(x[-1])  # Tambahkan nilai fungsi di batas

# Hitung nilai fungsi pada titik-titik tengah
for i in range(1, n-1, 2):  # Untuk indeks ganjil
    hasil += 4 * func(x[i])
for i in range(2, n-2, 2):  # Untuk indeks genap
    hasil += 2 * func(x[i])

# Kalikan dengan faktor dx/3
hasil *= dx / 3

# Visualisasi grafik dan bar
x_plot = np.linspace(a, b, 100)
plt.plot(x_plot, func(x_plot))

for i in range(n):
    plt.bar(x[i], func(x[i]), align='edge', width=dx, color='red', edgecolor='black')

plt.show()

print("Hasil integral:", hasil)