# -*- coding: utf-8 -*-
"""Tugas 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ewI2eyUtQklPBPnfnNgjSXMJRiJegSq
"""

# Mengimport library
import numpy as np
import matplotlib.pyplot as plt

def func(x):
    return x**-3 + np.cos(x)
a = 1.0  #batas bawah
b = 5.0 #batas atas

n = 150
dx = (b-a)/(n-1)
x = np.linspace(a,b,n)

sigma = 0
for i in range(1, n-1):
    sigma += func(x[i])

hasil = 0.5*dx*(func(x[0])+2*sigma+func(x[-1]))
print(hasil)

xp = np.linspace(a,b,1000)
plt.plot(xp,func(xp))
plt.show()

xp = np.linspace(a,b,1000)
plt.plot(xp,func(xp))
for i in range(n):
    plt.bar(x[i], func(x[i]), align='edge', width=0.000001, edgecolor='red')
plt.show()

xp = np.linspace(a, b, 1000)
plt.plot(xp, func(xp))

for i in range(n):
    plt.bar(x[i], func(x[i]), align='edge', width=0.000001, edgecolor='red')

plt.fill_between(x, func(x), color='yellow', alpha=0.5)
plt.show()